name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make pkg-config mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-portaudio mingw64/mingw-w64-x86_64-nsis bison flex zip unzip
      - name: Build with make
        run: make
      - name: Copy DLLs over
        run: cp $MSYSTEM_PREFIX/bin/libportaudio.dll .
      - name: Install NSIS EnvVar plugin
        run: (cd $MSYSTEM_PREFIX/share/nsis && wget https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip && unzip EnVar_plugin.zip && cp Plugins/amd64-unicode/EnVar.dll Plugins/unicode/EnVar.dll)
      - name: Replace version string
        run: sed -i -e 's/{{VERSION}}/'${{github.ref_name}}'/' mdxtools.nsi
      - name: Create NSIS installer
        run: makensis mdxtools.nsi
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mdxtools-${{github.ref_name}}.exe
